### ISSUE TITLE
FreeBSD Linux binary layer execution-Is info retrieval possible?

### ISSUE THREAD

**Issue by sugarykeytone** [TheDarkBug/uwufetch#131]
![linuxelf](https://user-images.githubusercontent.com/90227297/133866872-bac4b7be-65a6-44f3-9ca5-e3b7244af878.png)
FreeBSD has a Linux binary layer which works like it runs Linux natively, and uwufetch doesn't seem to recognize it's run from FreeBSD if I run the Linux ELF binary from it.
Is there any way to find out that's it's being run by a compatibility layer?

**Comment by TheDarkBug** [comment]
I think that it is not possible to detect a compatibility layer, but I'm not sure. Anyway uwufetch runs natively on freeBSD since 9d6f99d

**Comment by sugkiy** [comment]
I know, it compiles natively with gmake, I wasjust asking if the compatibility layer could be detected.

**Comment by TheDarkBug** [comment]
After some internet research, I couldn't find any way to detect the emulation layer.
Also if it was possible, how would uwufetch get the info? The linux way would not work, because some files do not exist on freebsd (and I doubt that they are in the emulation layer); also you can't use freebsd functions, because `<sys/sysctl.h>` is needed and it's a freebsd/mac os specific include.
I am not closing this issue because maybe someone has a different answer. I am not a bsd or linux expert, so I could be 100% wrong on this topic.

**Comment by TheDarkBug** [comment]
Issue closed due to inactivity
