### ISSUE TITLE
Taking long time to execute

### ISSUE THREAD

**Issue by mobilegmYT** [TheDarkBug/uwufetch#164]
I'm currently on WSL2 Debian, my PC doesn't have fabulous specs but the RAM and CPU usage was pretty low while I was running uwufetch. According to `time`, it took 2 minutes from running the command to getting a output!

![image](https://user-images.githubusercontent.com/44128563/141244944-ecca739c-33b7-4478-845e-9d72194a0099.png)

**Comment by TheDarkBug** [comment]
On my wsl system uwufetch works just like any other distro, so I can't reproduce the issue. Maybe the slowness is caused by some command that uwufetch runs while getting info. Could you try to run every command in [pkgman()](https://github.com/TheDarkBug/uwufetch/blob/main/uwufetch.c#L315)? So if one of this commands is the problem you can report it.

**Comment by mobilegmYT** [comment]
apt was the only one that worked, and it only took a few seconds to execute

**Comment by TheDarkBug** [comment]
I'm sorry, I don't really know why it is slow on your system. You could try to find the issue with gdb (if you know how to use it) or just use the cache (set UWUFETCH_CACHE_ENABLED=1).

**Comment by mobilegmYT** [comment]
The slowness goes away when I run it with `UWUFETCH_CACHE_ENABLED=1 uwufetch`.

**Comment by mobilegmYT** [comment]
A side effect of this is that it won't read any args I put into it. eg, if I do `uwufetch --help`, it just shows me the regular uwufetch stuff with my stats and the OS art.

**Comment by TheDarkBug** [comment]
That's because when that env variable is enabled, uwufetch reads and prints the cache without parsing the arguments
