### ISSUE TITLE
[BUG] Buffer overflow on NixOS

### ISSUE THREAD

**Issue by edgess73** [TheDarkBug/uwufetch#235]
**Describe the bug**
Buffer overflow detected, when runned

**To Reproduce**
1. Open nix shell with uwufetch
2. Run `uwufetch` in terminal

**Expected behavior**
uwufetch will run

**Screenshots**
![image](https://github.com/TheDarkBug/uwufetch/assets/87182103/f43529d0-9e64-4a73-a1c3-6d7a856d3558)

**Desktop (please complete the following information):**
 - OS: NixOS
 - Version 23.11 (nixos-unstable) and 23.05 (nixos-stable)

**Additional context**
Overflow happens on my laptop and friend's laptop with NixOS. Package version: 2.1 (from nixpkgs)

**Are you already working on this bug?**
Not working

**Comment by TheDarkBug** [comment]
I'm rewriting `fetch.c`, some things may be fixed or broken. The libfetch-rewrite branch will eventually be merged with main, so could you test uwufetch on that branch?
```bash
cd uwufetch
git checkout libfetch-rewrite
make
./uwufetch
```
Thanks

**Comment by edgess73** [comment]
It works, but OS is unknown and pkgs are not available.
![image](https://github.com/TheDarkBug/uwufetch/assets/87182103/db6e2db5-64d8-4bd3-be0b-c51dce3c0af9)

Thanks!

**Comment by TheDarkBug** [comment]
Thanks for the feedback.

The os does get recognized, but there is no ascii file for it ([partial support](https://github.com/TheDarkBug/uwufetch/tree/libfetch-rewrite#partial-support-either-no-ascii-art-or-no-image-is-provided)). After completing the `libfetch` rewrite, I'll create an ascii art (if no one makes one before I do).

Packages got fixed in c2882042f78e6c21688256cda725e103b2160486.
