### ISSUE TITLE
Solus prints both tuwux and sowolus images

### ISSUE THREAD

**Issue by ThatOneCalculator** [TheDarkBug/uwufetch#40]
UwU~ your p-pwogwam made a fucky wucky, owo!~

Pwease fix this code, senpai!! ^w^

![image](https://user-images.githubusercontent.com/44733677/111236842-0684bc80-85b1-11eb-8d43-064bcc015712.png)

**Comment by prettykool** [comment]
This problem lies in the fact that Solus, despite being included in the ``res`` file, isn't in the ``uwu_name`` function of uwufetch.c, and thereby ends up printing the unsupported distribution icon (tUwUx) along with it. Try adding this into ``uwu_name`` - it's at the end of ``uwufetch.c`` - and see if it fixes the problem:
```c
        else STRING_TO_UWU("solus", "sOwOlus ");
```

**Comment by Guaxinim5573** [comment]
@prettykool's solutions works great!
You should make a PR.

**Comment by TheDarkBug** [comment]
Fixed by #41 (thanks @prettykool)
